Update os.py
fix: ATTR_DATA_DISK: self.sys_os.datadisk.disk_used.id,
AttributeError: 'NoneType' object has no attribute 'id'
when update to 2023.03.03